name = "CrimeWave"
node = "dale"
batches = 4
root_vmid = 90
bridge = "vmbr1"

[machines.binex100]
name = "binex100"
template_vmid = 70002
destination_vmid = 30
mac_addr = "AA:BB:CC:DD:EE:1E"
lxc = true

[machines.forensics200]
name = "binex200"
template_vmid = 70003
destination_vmid = 31
mac_addr = "AA:BB:CC:DD:EE:1F"
lxc = true

[machines.forensics300]
name = "binex300"
template_vmid = 70004
destination_vmid = 32
mac_addr = "AA:BB:CC:DD:EE:20"
lxc = true

[machines.web100]
name = "vmtest100"
template_vmid = 20014
destination_vmid = 20
mac_addr = "AA:BB:CC:DD:EE:14"
lxc = false

[machines.web200]
name = "vmtest200"
template_vmid = 20014
destination_vmid = 21
mac_addr = "AA:BB:CC:DD:EE:15"
lxc = false

[machines.web300]
name = "vmtest300"
template_vmid = 20014
destination_vmid = 22
mac_addr = "AA:BB:CC:DD:EE:16"
lxc = false
